# Generated by Django 5.0.6 on 2024-07-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourse',
            name='materials',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='took_place',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
